---
- name: copy files from local to remote
  hosts: EC2INSTANCES
  become: true

  tasks:
  - name: copy .bashrc file to /home/ec2-user/.bashrc
    copy:
      src: .bashrc
      dest: /home/ec2-user/.bashrc
      owner: ec2-user
      group: ec2-user
      mode: '0644'

