---
- name: install httpd
  dnf:
    name: httpd
    state: present
- name: copy index.html to server
  copy:
    src: index.html
    dest: /var/www/html/index.html
    owner: root
    group: root
    mode: 0644

- name: start httpd
  service:
    name: httpd
    state: started
    enabled: true
